# Site
repository: petevdp/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Pieter Vanderpol
title: Full Stack Web Developer
location: Vancouver, BC
email: pjvanderpol@gmail.com
# phone: Your phone number (optional)
# website: Your website (eg. https://google.com)(optional)

# Social links
# twitter_username: jekyllrb
github_username: petevdp
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: pvanderpolwebdev
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Enthusiastic web developer with strong programming fundamentals. I take pride in writing concise, readable, and scalable code that solves problems, and I enjoy searching improving my workflow and knowledge related to my current project and the tech wold more generally. I'm interested in positions where I can contribute substantially as part of a team, and grow as a result.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Technologies
more_content: | # this will include new lines to allow paragraphs
  * __Languages__: Javascript(ES5/ES6), Python, C/C++, Ruby, SQL, Bash
  * __Front End__: CSS3, SCSS, HTML5, React, jQuery, Webpack
  * __Middleware__: NodeJS, Ruby On Rails
  * __Testing__: RSpec, Mocha, Jest, Capybara, Cypress, Pytest
  * __Database__: PostgreSQL, MongoDB
  * __DevOps__: Git, Docker, Vagrant, Linux

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme # (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "README.md",
    "LICENSE",
    "modern-resume-theme.gemspec",
    "screenshot.png",
  ]
